#!/bin/bash

# Sets up a local Ethereum testnet - this should be good for any unix install
# 1. TODO Checks to see if Ethereum is installed (if not then install)
# 2. Creates a conf file for the genesis.json and password files, if they do not exist
# 3. Creates a node using Geth with a discrete data_dir and port set.

# Add some variables
# networkid
networkid=1973
# node_id - to differentiate between configured nodes within a private network cluster
node_id=0
# IPC port
ipc_port=30801
# RPC port
rpc_port=8901
# data_dir
data_dir=/tmp/$networkid
# conf
conf=./conf
# pid for this node
pid_file=""

# Help
function usage {
    echo Usage:
    echo    testnet [param]
    echo params:
    echo    --create [node_id]: Creates a new testnet node. If within a cluster pass in a unique node_id - default is 0
    echo    --addacc [node_id] : Creates a account on the node. The first account is the coinbase account.
    echo    --unlockacc [account_no] [node_id] : Unlocks the account given TODO
    echo    --start [node_id] : Starts the local test node TODO
    echo    --stop [node_id] : Stops the local test node TODO
    echo    --attach [node_id] : attaches to a running node
    echo    --minestart [node_id] : starts the miner
    echo    --minestop [node_id] : stops the miner
    echo    --cluster : links all local nodes into a cluster
    echo    --clean [node_id] : Cleans the node installation back to base account
    echo    --cleanAll : Cleans the whole shebang
    echo    --help -h : This message
}
# Install Ethereum
function install-steps {
    if [[ $OSTYPE == darwin* ]]; then
        echo You\'re on a Mac, you can install using:
        echo "brew tap ethereum/ethereum &&"
        echo "brew install ethereum"
    elif [[ $OSTYPE == linux-gnu ]]; then
        echo You\'re on a Ubuntu variant, you can install using:
        echo "  sudo add-apt-repository ppa:ethereum/ethereum-qt &&"
        echo "  sudo add-apt-repository ppa:ethereum/ethereum &&"
        echo "  sudo add-apt-repository ppa:ethereum/ethereum-dev &&"
        echo "  sudo apt-get update &&"
        echo "  sudo apt-get install cpp-ethereum &&"
        echo "  sudo apt-get install ethereum"
    else # This is not supported
        echo Sorry, check the Ethereum docs for your Operating system
    fi
    exit
}
function checkEthereum {

    if [ hash geth >/dev/null 2>&1 || hash eth >/dev/null 2>&1 ]; then
        echo No current installation of Ethereum
        install-steps
    else
        echo Already installed Ethereum, nice! Proceeding...
    fi
}
# Configure
function configure {
    # Create the required directories and files if not there
    if [ "$(ls -A $conf 2>/dev/null)" ]; then
        echo $conf already exists, not creating
    else
        echo Creating the local conf directory and files to configure node
        mkdir $conf
        genesis_block='{
            "nonce": "0x0000000000000042",
            "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "difficulty": "0x4000",
            "alloc": {},
            "coinbase": "0x0000000000000000000000000000000000000000",
            "timestamp": "0x00",
            "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "extraData": "Custom Ethereum Genesis Block for initiating a local test net",
            "gasLimit": "0xffffffff"
        }'
        echo $genesis_block > $conf/genesis_block.json
        echo 'testpwd-01' > conf/testnet-pwd
    fi
    if [ "$(ls -A $data_dir 2>/dev/null)" ]; then
        echo $data_dir already exists, not creating.
        echo If you want to re-create, run $0 --clean
    else
        echo Creating the node data_dir at $data_dir
        mkdir -p $data_dir
    fi
}
# Create
function create {
    if [ -z "$1" ]; then
        echo No node_id passed in, using default - $node_id;
    else
        let node_id=$1
        echo New node will be created: $node_id
    fi
    data_dir=$data_dir/$node_id
    pid_file=$data_dir/pid-file
    let ipc_port=$ipc_port+$node_id
    let rpc_port=$rpc_port+$node_id

    echo Checking that Ethereum is installed
    checkEthereum
    configure
    echo Starting node: $node_id, with ipc port: $ipc_port and rpc port: $rpc_port at data dir: $data_dir
    start
}
# Start node
function start {
    if [ -z "$1" ]; then
        echo No node_id passed in, using default - $node_id;
    else
        let node_id=$1
        echo New node will be created: $node_id
    fi
    echo Starting local testnet node: $node_id...
    
    geth --genesis $conf/genesis_block.json --datadir $data_dir --networkid $networkid --port $ipc_port --rpcport $rpc_port --nodiscover 2>> $data_dir/eth.log & echo $! >> $pid_file
    echo Done. Geth should now be running with pid: $(more $pid_file). See $data_dir/eth.log for details

}
# Stop node
function stop {
    # TODO handle the node_id param
    echo Stopping node...
    if [ -n "$(more $pid_file)" ]; then
        kill -HUP $(more $pid_file)
        echo ...done.
    fi
}
# Attach
function attach {
    echo attaching to ipc endpoint $data_dir/geth.ipc
    geth attach ipc:$data_dir/geth.ipc
}
# Add account
function addacc {
    echo Adding account...
    geth --datadir $data_dir --networkid $networkid --port $ipc_port --rpcport $rpc_port --password $conf/testnet-pwd account new
}
# Starts the miner on the designated node
function startmining {
    echo starting the miner on this node: $networkid:$ipc_port
    echo NOT IMPLEMENTED
}
# Stop the miner on the designated node
function stopmining {
    echo stopping the miner on this node: $networkid:$ipc_port
    echo NOT IMPLEMENTED
}
# Unlock account
function unlockacc {
    if [ -z "$2" ]; then
        echo No account passed in, exiting;
        exit
    else
        echo unlocking $2
        echo NOT IMPLEMENTED
        # geth --password ./conf/testnet-pwd --unlock $2  --networkid 1973 --port 30801 --rpcport 8901
    fi
}
# Cluster the known nodes
function cluster {
    echo NOT IMPLEMENTED
}
# Clean
function clean {
    # TODO take a node param
    echo Cleaning $data_dir...
    rm -rf $data_dir
    echo ...done.
}
if [ -z "$1" ]; then
    usage
    exit
fi
if [[ "$1" == "--create" ]]; then
    create $2;
elif [[ "$1" == "--addacc" ]]; then
    addacc;
elif [[ "$1" == "--unlockacc" ]]; then
    unlockacc;
elif [[ "$1" == "--start" ]]; then
    start;
elif [[ "$1" == "--stop" ]]; then
    stop;
elif [[ "$1" == "--attach" ]]; then
    attach;
elif [[ "$1" == "--minestart" ]]; then
    startmining;
elif [[ "$1" == "--minestop" ]]; then
    stopmining;
elif [[ "$1" == "--cluster" ]]; then
    cluster;
elif [[ "$1" == "--clean" ]]; then
    clean;
elif [[ "$1" == "--help" ]]; then
    usage;
elif [[ "$1" == "-h" ]]; then
    usage;
else
        echo Unknown command.
        usage
        exit
fi
