FROM avastmick/general-dev

MAINTAINER avastmick <avastmick.outlook.com>

WORKDIR /usr/local/repos/

RUN apt-get update && \
    apt-get upgrade -q -y && \
    apt-get dist-upgrade -q -y && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 923F6CA9 && \
    echo "deb http://ppa.launchpad.net/ethereum/ethereum-dev/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/ethereum.list && \
    apt-get update && \
    apt-get install -q -y geth && \
    apt-get update && \
    apt-get install -q -y git && \
    # Now clone the ethereum-local-testnet repo
    git clone https://github.com/avastmick/ethereum-local-testnet.git && \
    # And run testnet
    cd ethereum-local-testnet && \
    ./testnet --create

ENTRYPOINT /usr/local/repos/ethereum-local-testnet
